pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        
        stage('Package') { 
            steps{
                
    xldCreatePackage artifactsPath: '/var/jenkins_home/workspace', manifestPath: 'deployit-manifest.xml', darPath: 'my-app-1.0-$BUILD_NUMBER.0-SNAPSHOT.jar'  
                
             }
        }      
    }
}
